# Generated by Django 4.1.5 on 2023-01-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychomatrixAdditionalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=55, unique=True)),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('annotation', models.CharField(blank=True, max_length=4096, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=10240, null=True)),
            ],
            options={
                'db_table': 'psychomatrix_additional_contents',
            },
        ),
        migrations.CreateModel(
            name='PsychomatrixBaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=55, unique=True)),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('text', models.CharField(blank=True, max_length=10240, null=True)),
                ('advice', models.CharField(blank=True, max_length=4096, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'psychomatrix_basic_contents',
            },
        ),
    ]
