# Generated by Django 4.1.7 on 2023-03-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychomatrix', '0002_celebrities_psychomatrixbasecelebrity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='psychomatrixadditionalcelebrity',
            table='psychomatrix_additional_celebrity',
        ),
        migrations.AlterModelTable(
            name='psychomatrixbasecelebrity',
            table='psychomatrix_base_celebrity',
        ),
    ]
