# Generated by Django 4.1.7 on 2023-03-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychomatrix', '0003_alter_psychomatrixadditionalcelebrity_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celebrities',
            new_name='Celebrity',
        ),
    ]
