# Generated by Django 4.1.7 on 2023-03-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychomatrix', '0004_rename_celebrities_celebrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='photo',
            field=models.ImageField(default=1, upload_to='psychomatrix/'),
            preserve_default=False,
        ),
    ]
